import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { ArrowRight, Calculator } from 'lucide-react'
import { getCostEstimate, getHospitals, getTreatments } from '../api'
import { DataState } from '../components/DataState'

export function CostCalculator() {
  const treatments = useQuery({ queryKey: ['calculator-treatments'], queryFn: () => getTreatments() })
  const [treatmentId, setTreatmentId] = useState('')
  const [hospitalId, setHospitalId] = useState('')
  const providers = useQuery({ queryKey: ['calculator-hospitals', treatmentId], queryFn: () => getHospitals({ treatmentId }), enabled: Boolean(treatmentId) })
  const estimate = useQuery({ queryKey: ['cost-estimate', treatmentId, hospitalId], queryFn: () => getCostEstimate(treatmentId, hospitalId), enabled: Boolean(treatmentId && hospitalId) })
  return <><main className="calculator-page"><div className="calculator-intro"><span className="kicker">Transparent planning</span><h1>Plan with an estimate, not a promise.</h1><p>Use current hospital treatment data to understand the likely range before speaking with a provider.</p></div><section className="calculator-panel"><div className="calculator-icon"><Calculator size={22} /></div><div className="calculator-fields"><label>Treatment<select value={treatmentId} onChange={(event) => { setTreatmentId(event.target.value); setHospitalId('') }}><option value="">Choose a treatment</option>{treatments.data?.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Verified hospital<select value={hospitalId} onChange={(event) => setHospitalId(event.target.value)} disabled={!treatmentId}><option value="">Choose a hospital</option>{providers.data?.map((hospital) => <option value={hospital.id} key={hospital.id}>{hospital.name} · {hospital.city}</option>)}</select></label></div><DataState loading={estimate.isLoading} error={estimate.error} empty={treatmentId && hospitalId ? 'No estimate available for this provider.' : 'Choose a treatment and hospital to calculate.'}>{estimate.data && <div className="estimate-result"><span>Estimated treatment total</span><strong>{estimate.data.hospitalTreatment.currency} {Number(estimate.data.minimumEstimatedTotal).toLocaleString('en-IN')} – {estimate.data.hospitalTreatment.currency} {Number(estimate.data.maximumEstimatedTotal).toLocaleString('en-IN')}</strong><div><span>Hospital treatment range</span><span>{estimate.data.hospitalTreatment.minEstimatedCost ? `₹${Number(estimate.data.hospitalTreatment.minEstimatedCost).toLocaleString('en-IN')} – ₹${Number(estimate.data.hospitalTreatment.maxEstimatedCost || estimate.data.hospitalTreatment.minEstimatedCost).toLocaleString('en-IN')}` : 'On request'}</span></div><div><span>Consultation estimate</span><span>₹{Number(estimate.data.consultationEstimate).toLocaleString('en-IN')}</span></div></div>}</DataState><p className="medical-disclaimer">{estimate.data?.disclaimer || "Estimated cost only. Final cost depends on medical assessment and the hospital's final quotation."}</p></section></main></>
}
