import { useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { ArrowRight } from 'lucide-react'
import { api } from '../api'
import { DataState } from '../components/DataState'

export function HospitalComparison() {
  const [params] = useSearchParams()
  const treatmentId = params.get('treatmentId')
  const [sort, setSort] = useState('recommended')
  const query = useQuery({ queryKey: ['release3-compare', treatmentId, sort], queryFn: async () => (await api.get('/public/compare/hospitals', { params: { treatmentId, sort } })).data.data, enabled: Boolean(treatmentId) })
  const count = query.data?.availableHospitalCount || 0
  return <><main className="detail-page"><span className="kicker">Patient discovery</span><h1>Compare verified hospitals.</h1><p className="detail-lede">Only real hospitals with approved, available treatment records appear here. This comparison is informational, not medical advice.</p><div className="comparison-toolbar"><span>{count === 0 ? 'No verified hospitals currently offer this treatment.' : count === 1 ? '1 verified hospital currently offers this treatment.' : `${count} verified hospitals currently offer this treatment.`}</span><label>Sort<select value={sort} onChange={(event) => setSort(event.target.value)}><option value="recommended">Recommended</option><option value="lowest-cost">Lowest estimated cost</option><option value="highest-cost">Highest estimated cost</option><option value="shortest-stay">Shortest hospital stay</option></select></label></div><DataState loading={query.isLoading} error={query.error} empty="Select a treatment to compare verified providers.">{query.data?.comparisonEnabled ? <div className="comparison-table"><div className="comparison-head"><span>Care detail</span>{query.data.hospitals.map((entry) => <strong key={entry.id}>{entry.hospital.name}</strong>)}</div>{[['City', (entry) => `${entry.hospital.city}, ${entry.hospital.country}`], ['Treatment', (entry) => entry.treatment.name], ['Estimated cost', (entry) => entry.minEstimatedCost ? `₹${Number(entry.minEstimatedCost).toLocaleString('en-IN')} – ₹${Number(entry.maxEstimatedCost || entry.minEstimatedCost).toLocaleString('en-IN')}` : 'On request'], ['Hospital stay', (entry) => entry.hospitalStay || 'On request'], ['Accreditation', (entry) => entry.hospital.accreditation || 'Not provided'], ['Facilities', (entry) => entry.hospital.facilities || 'Not provided'], ['International support', (entry) => entry.hospital.internationalSupport ? 'Available' : 'Contact hospital'], ['Availability', () => 'Available']].map(([label, value]) => <div className="comparison-row" key={label}><span>{label}</span>{query.data.hospitals.map((entry) => <div key={entry.id}>{value(entry)}</div>)}</div>)}</div> : count === 1 ? <div className="data-state">Comparison is disabled because only one verified hospital offers this treatment.</div> : <div className="data-state">No verified hospitals currently offer this treatment.</div>}</DataState><Link className="inline-link comparison-back" to="/treatments">Back to treatments <ArrowRight size={15} /></Link></main></>
}
