import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { io } from 'socket.io-client'
import { ArrowRight, FileText } from 'lucide-react'
import { confirmAppointment, getHospitalCases, sendHospitalResponse, updateCaseStatus } from '../api'
import { DataState } from '../components/DataState'

function HospitalChat({ conversation }) {
  const [messages, setMessages] = useState(conversation?.messages || [])
  const [content, setContent] = useState('')
  useEffect(() => { if (!conversation?.id) return undefined; const socket = io('/', { withCredentials: true }); socket.emit('conversation:join', { conversationId: conversation.id }); socket.on('message:new', (message) => setMessages((items) => [...items, message])); return () => socket.disconnect() }, [conversation?.id])
  const send = () => { if (!content.trim() || !conversation?.id) return; const socket = io('/', { withCredentials: true }); socket.emit('conversation:join', { conversationId: conversation.id }); socket.emit('message:send', { conversationId: conversation.id, content }); setContent(''); setTimeout(() => socket.disconnect(), 400) }
  return <div className="chat-panel"><h3>Patient chat</h3><div className="chat-messages">{messages.map((message) => <p key={message.id}><strong>{message.senderId === conversation.hospitalId ? 'Hospital' : 'Patient'}:</strong> {message.content}</p>)}</div><div className="chat-compose"><input value={content} onChange={(event) => setContent(event.target.value)} placeholder="Reply to patient" /><button className="button button-dark" onClick={send}>Send</button></div></div>
}

export function HospitalCaseManagement() {
  const query = useQuery({ queryKey: ['hospital-cases'], queryFn: getHospitalCases })
  const [responses, setResponses] = useState({})
  const update = (id, key, value) => setResponses({ ...responses, [id]: { ...responses[id], [key]: value } })
  return <main className="dashboard-page"><div className="dashboard-main workflow-page"><span className="kicker">Hospital workspace</span><h1>Assigned patient cases.</h1><p className="detail-lede">Only cases submitted to your hospital are visible here. Medical reports remain private and authorized to this hospital only.</p><DataState loading={query.isLoading} error={query.error} empty="No patient cases have been assigned."><div className="hospital-case-list">{query.data?.map((item) => { const form = responses[item.id] || {}; return <article className="dashboard-panel hospital-case-card" key={item.id}><div className="panel-heading"><div><span className="status-pill">{item.status}</span><h2>{item.treatment.name}</h2><p>{item.patient.firstName} {item.patient.lastName} · {new Date(item.createdAt).toLocaleDateString()}</p></div><select value={item.status} onChange={async (event) => { await updateCaseStatus(item.id, event.target.value); query.refetch() }}><option value="SUBMITTED">Submitted</option><option value="UNDER_REVIEW">Under review</option><option value="RESPONDED">Responded</option><option value="COMPLETED">Completed</option><option value="CANCELLED">Cancelled</option></select></div><div className="report-list"><strong><FileText size={15} /> Authorized reports</strong>{item.reports?.map((report) => <p key={report.id}>{report.originalName} · {report.category}</p>)}</div><form className="case-form" onSubmit={async (event) => { event.preventDefault(); await sendHospitalResponse(item.id, form); query.refetch() }}><label>Case summary<textarea required value={form.summary || ''} onChange={(event) => update(item.id, 'summary', event.target.value)} /></label><label>Recommended next step<textarea required value={form.recommendedNextStep || ''} onChange={(event) => update(item.id, 'recommendedNextStep', event.target.value)} /></label><div className="form-grid"><label>Estimated cost<input type="number" min="0" value={form.estimatedTreatmentCost || ''} onChange={(event) => update(item.id, 'estimatedTreatmentCost', event.target.value)} /></label><label>Estimated stay<input value={form.estimatedHospitalStay || ''} onChange={(event) => update(item.id, 'estimatedHospitalStay', event.target.value)} /></label></div><button className="button button-coral">Send response <ArrowRight size={16} /></button></form>{item.appointments?.map((appointment) => <div className="appointment-row" key={appointment.id}><span>Appointment request: {new Date(appointment.preferredAt).toLocaleString()}</span><button className="button button-dark button-small" onClick={async () => { await confirmAppointment(appointment.id, 'CONFIRMED'); query.refetch() }}>Confirm</button></div>)}<HospitalChat conversation={item.conversation} /><Link className="inline-link" to={`/hospital/cases/${item.id}`}>Open case details <ArrowRight size={15} /></Link></article> })}</div></DataState></div></main>
}
